// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class VwProductoConfiguration : IEntityTypeConfiguration<VwProducto>
    {
        public void Configure(EntityTypeBuilder<VwProducto> entity)
        {
            entity.HasNoKey();

            entity.ToView("vwProducto");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.IdProducto).ValueGeneratedOnAdd();

            entity.Property(e => e.Importe).HasColumnType("numeric(18, 2)");

            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwProducto> entity);
    }
}
