// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class VwProveedorConfiguration : IEntityTypeConfiguration<VwProveedor>
    {
        public void Configure(EntityTypeBuilder<VwProveedor> entity)
        {
            entity.HasNoKey();

            entity.ToView("vwProveedor");

            entity.Property(e => e.Cuit)
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasColumnName("CUIT");

            entity.Property(e => e.Domicilio)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.FechaAlta).HasColumnType("datetime");

            entity.Property(e => e.FechaBaja).HasColumnType("datetime");

            entity.Property(e => e.IdProveedor).ValueGeneratedOnAdd();

            entity.Property(e => e.Provincia)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.RazonSocial)
                .HasMaxLength(100)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwProveedor> entity);
    }
}
