// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class VwProductoVendidoConfiguration : IEntityTypeConfiguration<VwProductoVendido>
    {
        public void Configure(EntityTypeBuilder<VwProductoVendido> entity)
        {
            entity.HasNoKey();

            entity.ToView("vwProductoVendido");

            entity.Property(e => e.IdProductoVendido).ValueGeneratedOnAdd();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwProductoVendido> entity);
    }
}
