// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class VwVentaConfiguration : IEntityTypeConfiguration<VwVenta>
    {
        public void Configure(EntityTypeBuilder<VwVenta> entity)
        {
            entity.HasNoKey();

            entity.ToView("vwVenta");

            entity.Property(e => e.Total).HasColumnType("numeric(18, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwVenta> entity);
    }
}
